/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("rafael.kotlin-application-conventions")
}

dependencies {
    implementation("io.ktor:ktor-server-core:1.5.3")
    implementation("io.ktor:ktor-server-netty:1.5.3")
  //  implementation("io.netty:netty-transport-native-kqueue:4.1.63.Final:osx-x86_64")
    implementation("ch.qos.logback:logback-classic:1.2.3")
}

application {
    // Define the main class for the application.
    mainClass.set("rafael.app.AppKt")
}
